---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 1.0.3
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Importing datasets


We will use two datasets which are freely available. The [Iris](https://archive.ics.uci.edu/ml/datasets/iris) and [Wine Reviews](https://www.kaggle.com/zynicide/wine-reviews) dataset, which we can both load in using pandas `read_csv` method.

```{python}
import pandas as pd
```

```{python}
iris = pd.read_csv('Dataset\iris.csv', names=['sepal_length','sepal_width','petal_length','petal_width','class'])
iris.head()
```

```{python}
wine_reviews = pd.read_csv('Dataset\winemag-data-130k-v2.csv', index_col=0)
wine_reviews.head()
```

# Matplotlib


Matplotlib is the most popular python plotting library. It is a low-level library with a Matlab like interface which offers lots of freedom at the cost of having to write more code. 

To install Matplotlib pip and conda can be used. 

```
pip install matplotlib
or
conda install matplotlib
```

Matplotlib is good for creating basic graphs like line charts, bar charts, histograms and many more. It can be imported by typing:

```{python}
import matplotlib.pyplot as plt
```

## Scatter plot

To create a scatter plot in Matplotlib we can use the `scatter` method. We will also create a figure and an axis using `plt.subplots` so we can give our plot a title and labels. 

```{python}
# create a figure and axis
fig, ax = plt.subplots()

# scatter the sepal_length against the sepal_width
ax.scatter(iris['sepal_length'],iris['sepal_width'])

# set title and labels
ax.set_title('Iris Dataset')
ax.set_xlabel('Sepal Length')
ax.set_ylabel('Sepal Width')
```

We can give the graph more meaning by coloring each point by its class. This can be done by creating a dictionary which maps from class to color and then scattering each point on its own using for-loop and passing respective color. 

```{python}
# create color dictionary
colors = {'Iris-setosa':'r', 'Iris-versicolor':'g', 'Iris-virginica':'b'}

# create figure and axis
fig, ax = plt.subplots()

# plot each data point
for i in range(len(iris['sepal_length'])):
    ax.scatter(iris['sepal_length'][i], iris['sepal_width'][i], color=colors[iris['class'][i]])

# set title and labels
ax.set_title('Iris Dataset')
ax.set_xlabel('Sepal Length')
ax.set_ylabel('Sepal Width')
```

## Line chart

In Matplotlib we can create a line chart by calling the `plot` method. We can also plot multiple columns in one graph, by looping through the columns we want and plotting each column on the same axis. 

```{python}
# get columns to plot
columns = iris.columns.drop(['class'])

# create x data
print('Iris shape:', iris.shape)
x_data = range(0, iris.shape[0])

# create figure and axis
fig, ax = plt.subplots()

# plot each column
for column in columns:
    ax.plot(x_data, iris[column])

# set title and legend
ax.set_title('Iris Dataset')
ax.legend()
```

## Histogram

In Matplotlib we can create a Histogram using the `hist` method. If we pass it categorical data like the points column from the wine-review dataset it will automatically calculate how often each class occurs

```{python}
# create figure and axis
fig, ax = plt.subplots()

# plot histogram
ax.hist(wine_reviews['points'])

# set title and labels
ax.set_title('Wine Review Scores')
ax.set_xlabel('Points')
ax.set_ylabel('Frequency')
```

## Bar chart

A bar chart can be created using `bar` method. The bar chart isn't automatically calculating the frequency of a category so we are going to use pandas `value_counts` function to do this. The bar chart is useful for categorical data that doesn't have a lot of different categories (less than 30) otherwise it gets messy. 

```{python}
# create a figure and axis
fig, ax = plt.subplots()

# count the occurrence of each class
data = wine_reviews['points'].value_counts()

# get x and y data
points = data.index
frequency = data.values

# create a bar chart
ax.bar(points, frequency)

# set title and labels
ax.set_title('Wine review scores')
ax.set_xlabel('Points')
ax.set_ylabel('Frequency')
```

# Pandas visualisation

Pandas Visualisation makes it easy to create plots out of a pandas dataframe and series. It also has a higher level API than Matplotlib and therefore we need less code for the same results. 


## Scatter plot

To create a scatter plot in Pandas, we can call `<dataframe>.plot.scatter()` and pass it two arguments, the name of x-column as well as the name of y-column. Optionally, we can also pass it ia title. 

```{python}
iris.plot.scatter(x='sepal_length', y='sepal_width', title='Iris Dataset')
```

As we can see in the graph, it is automatically setting the x and y label to the column names. 


## Line chart
To create line chart in Pandas we can call `<dataframe>.plot.line()`. Whilst in Matplotlib, we needed to loop-through each column we wanted to plot, in Pandas we don't need to do this because it automatically plot all available numeric columns. 

```{python}
iris.drop(['class'], axis=1).plot.line(title='Iris dataset')
```

If we have more than one feature, Pandas automatically creates a legend for us, as can be seen in the image above.


## Histogram
In Pandas, we can create Histogram with the `plot.hist` method. There aren't any required arguments but we can optionally pass some like the bin size. 

```{python}
wine_reviews['points'].plot.hist()
```

It's also easy to plot multiple histograms.

```{python}
iris['sepal_length'].plot.hist(bins=20)
```

```{python}
iris.plot.hist(subplots=True, layout=(2,2), figsize=(10,10), bins=20)
```

The `subplots` argument specifies that we want separate plot for each feature and `layout` specifies the number of plots per row and column.


## Bar chart
To plot a bar chart we use `plot.bar()` method, but before we can call this we need to get the data. For this, we will first count the occurrences using `value_counts()` method and then sort in ascending order using `sort_index()` method.  

```{python}
wine_reviews['points'].value_counts().sort_index().plot.bar()
```

It's also really easy to plot horizontal bar chart using `plot.barh()` method. 

```{python}
wine_reviews['points'].value_counts().sort_index().plot.barh()
```

We can also plot other data then the number of occurrences. 

```{python}
wine_reviews.groupby('country').price.mean().sort_values(ascending=False)[:5].plot.bar()
```

In the example above we grouped the data by country and then took the mean of the wine prices, ordered it, and plotted top 5 countries with the highest average wine price.


# Seaborn
Seaborn is a Python data visualisation library based on Matplotlib. It provides high level interface for creating attractive graphs. 
It can be imported by typing:

```{python}
import seaborn as sns
```

## Scatter plot
We can use `.scatterplot` method for creating a scatterplot, and just as in Pandas we need to pass it the column names of the x and y data, but now we also need to pass the data as an additional argument because we aren't calling the function on the data directly as we did in Pandas. 

```{python}
sns.scatterplot(x='sepal_length', y='sepal_width', data=iris)
```

We can also highlight the points by class using the `hue` argument, which is a lot easier than in Matplotlib

```{python}
sns.scatterplot(x='sepal_length',y='sepal_width',hue='class',data=iris)
```

## Line chart
To create a line chart the `sns.lineplot` method can be used. The only required argument is the data, which in our case are the four numeric columns from the Iris dataset. We could also use the `sns.kdeplot` method which rounds of the edges of the curves and therefore is cleaner if you have a lot of outliers in your dataset

```{python}
sns.lineplot(data = iris.drop(['class'], axis=1))
```

## Histogram
To create a histogram in Seaborn we use the `sns.displot` method. We need to pass it the column we want to plot and it will calculate the occurrences itself. We can also pass it the number of bins, and if we want to plot a gaussian kernel density estimate inside the graph.

```{python}
sns.distplot(wine_reviews['points'], bins=10, kde=False)
```

```{python}
sns.distplot(wine_reviews[('points')], bins=10, kde=True)
```

## Bar chart
In Seaborn a bar chart can be created using the `sns.countplot` method and passing it the data. 

```{python}
sns.countplot(wine_reviews['points'])
```

## Box plot
A box plot is a graphical method of displaying the five-number summary. We can create box plots using seaborns `sns.boxplot` method and passing it the data as well as the x and y column name. 

```{python}
df = wine_reviews[(wine_reviews['points']>=95) & (wine_reviews['price']<=1000)]
sns.boxplot('points','price',data=df)
```

Box plots just like bar chart are great for data with only a few categories but can get messy really quickly. 


## Heatmap
A Heatmap is a graphical representation of data where the individual values contained in a matrix are represented as colors. Heatmaps are perfect for exploring the correlation of features in a dataset. 

To get the correlations of the features inside a dataset we can call `<dataset>.corr()`, which is a Pandas dataframe method. This will give us the correlation matrix. 

We can now use either Matplotlib or Seaborn to create the Heatmap


### Matplotlib:

```{python}
import numpy as np
```

```{python}
# get correlation matrix
corr = iris.corr()

fig, ax = plt.subplots()

# create heatmap
im = ax.imshow(corr.values)

# Set labels
ax.set_xticks(np.arange(len(corr.columns)))
ax.set_yticks(np.arange(len(corr.columns)))
ax.set_xticklabels(corr.columns)
ax.set_yticklabels(corr.columns)

# Rotate the tick labels and set their alignment
plt.setp(ax.get_xticklabels(), rotation=45, ha="right", rotation_mode="anchor")
```

To add annotations to the heatmap, we need to add two for loops

```{python}
# get correlation matrix
corr = iris.corr()

fig, ax = plt.subplots()

im = ax.imshow(corr.values)

# Set labels
ax.set_xticks(np.arange(len(corr.columns)))
ax.set_yticks(np.arange(len(corr.columns)))
ax.set_xticklabels(corr.columns)
ax.set_yticklabels(corr.columns)

# Rotate the tick labels and set their alignment
plt.setp(ax.get_xticklabels(), rotation=45, ha="right", rotation_mode="anchor")

for i in range(len(corr.columns)):
    for j in range(len(corr.columns)):
        text = ax.text(j, i, np.around(corr.iloc[i,j], decimals=2), ha="center", va="center", color="black")
```

### Seaborn
Seaborn makes it way easier to create a heatmap and add annotations

```{python}
sns.heatmap(iris.corr(), annot=True)
```

## Faceting
Faceting is the act of breaking data variables up across multiple subplots and combining those subplots into a single figure. 

Faceting is really helpful if you want to quickly explore your dataset. 

To use one kind of Faceting in Seaborn, we can use the `FacetGrid`. First of all, we need to define the `FacetGrid` and pass it our data as well as row or column, which will be used to split the data. Then we need to call the `map` function on our `FacetGrid` object and define the plot type we want to use, as well as the column we want to graph. 

```{python}
g = sns.FacetGrid(iris, col='class')
g = g.map(sns.kdeplot, ('sepal_length'))
```

## Pairplot
Seaborn's `pairplot` and Pandas `scatter_matrix`, can be used to plot a grid of pairwise relationships in a dataset.

```{python}
sns.pairplot(iris)
```

```{python}
from pandas.plotting import scatter_matrix

fig, ax = plt.subplots(figsize=(12,12))
scatter_matrix(iris, alpha=1, ax=ax)
```

```{python}

```
